# MovieNight 2.0

# Sets the port which we will bind to.
# This applies to both the web front-end and also the API:
port=8181

# The parent directory where media files live:
mediaDir=/opt/MovieNight

# The directory for media group thumbnails:
thumbnailDir=/opt/MovieNight/thumbnails

# Our SQLite database file:
dbFile=/opt/MovieNight/MovieNight.db

# How many items to return per page in the API:
pageSize=8

# The web UI can always be found at /
# The API can be found at this base path:
apiBasePath=/MovieNight/

# The maximum size of HTTP range requests when streaming, in Megabytes.
# Increase this if you have a fast local network and regularly stream very large files.
rangeLimitMB=32
